### ISSUE TITLE
V9 parser not working

### ISSUE THREAD

**Issue by browsified** [mikemiles-dev/netflow_parser#105]
hello!

i've tried to generate v9 byte data 9 ways to Sunday, and i can't seem to get the parser to work correctly; no fields are extracted except the headers. I also don't see a v9 example whereas i can validate the format i am ingesting.

Any help/confirmation that can be lended would be great!

**Comment by mikemiles-dev** [comment]
Hi!  Are you talking about the V9 byte re-export?

**Comment by mikemiles-dev** [comment]
Can you provide some example data and/or some example code?

**Comment by browsified** [comment]
no, original ingest. Here is an example


let netflow_v9_packet: [u8; 72] = [
    // Header (20 bytes)
    0, 9,               // Version 9 (2 bytes)
    0, 2,               // FlowSet Count (2 FlowSets in this packet, 2 bytes)
    0, 0, 0, 100,       // Sys Uptime (100 ms, 4 bytes)
    0, 0, 0, 161,       // Unix Timestamp (161 seconds, 4 bytes)
    0, 1, 0, 1,         // Sequence Number (1) and Source ID (1), 4 bytes

    // FlowSet 1: Template FlowSet (ID 1)
    0, 1,               // FlowSet ID (Template FlowSet ID = 1, 2 bytes)
    0, 12,              // FlowSet Length (12 bytes), 2 bytes
    0, 1,               // Template ID (1), 2 bytes
    0, 8,               // Template Length (8 bytes), 2 bytes

    // FlowSet 2: Data FlowSet (ID 2)
    0, 2,               // FlowSet ID (Data FlowSet ID = 2, 2 bytes)
    0, 16,              // FlowSet Length (16 bytes), 2 bytes

    // Flow Record Data:
    0, 0, 0, 1,         // Source IP (192.168.0.1), 4 bytes
    0, 0, 0, 2,         // Destination IP (192.168.0.2), 4 bytes
    1, 80,              // Source Port (80), 2 bytes (big-endian)
    1, 187,             // Destination Port (443), 2 bytes (big-endian)
    0, 6,               // Protocol (TCP = 6), 2 bytes
    0, 0, 0, 100,       // Bytes (100 bytes), 4 bytes
    0, 0, 0, 10,        // Packets (10 packets), 4 bytes

    // Padding bytes to ensure the packet length is 72 bytes
    0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 
];

i also tried


    let packet: [u8; 80] = [
        0x00, 0x09, 0x00, 0x02, 0x00, 0x00, 0x00, 0x64, // Header: version, flow set count, uptime (100ms)
        0x00, 0x00, 0x00, 0xa1, 0x00, 0x01, 0x00, 0x01, // Header: timestamp, seq number, source ID
        0x00, 0x01, 0x00, 0x0C, 0x00, 0x01, 0x00, 0x08, // Template FlowSet: FlowSet ID, Length, Template ID
        0x00, 0x02, 0x00, 0x14, 0x00, 0x00, 0x00, 0x01, // Data FlowSet: FlowSet ID, Length, Source IP (192.168.0.1)
        0x00, 0x00, 0x00, 0x02, 0x00, 0x50, 0x01, 0x7B, // Data FlowSet: Destination IP (192.168.0.2), SrcPort(80), DstPort(443)
        0x00, 0x06, 0x00, 0x00, 0x00, 0x64, 0x00, 0x00, // Data FlowSet: Protocol (TCP), Bytes (100), Packets (10)
        0x00, 0x0A, 0x00, 0x00, 0x00, 0x10, 0x00, 0x20, // Data FlowSet: SrcAS (100), DstAS (200), InputIface (16), OutputIface (32)
        0x00, 0x30, 0x00, 0x40  // Data FlowSet: TOS (48), DSCP (64)
    ];


to no avail. I'm guessing i am missing something, somewhere.

**Comment by browsified** [comment]
i get the header data, but i dont get anything else, no templates, options, data, etc....

**Comment by mikemiles-dev** [comment]
So if you do not provide it the template flow that has the information on how to dissect fields , it cannot parse the flows.  So you will have to provide that flow that includes the template.

Additionally, you can also define the template yourself like so https://github.com/mikemiles-dev/netflow_parser/blob/main/src/tests.rs#L245

**Comment by browsified** [comment]
ahhh i see. So for V9 i need to define the fields, ok. Might be a silly question, but how do i know what fields i CAN map to? is that based on device? or could i just define ALL the fields in the spec and attempt to grab what i need?

**Comment by browsified** [comment]
in other words, would it be safe to add all fields and then attempt to grab them all? i understand they may not all exist

**Comment by browsified** [comment]
here is an example, and its probably my lack of exposure

let netflow_packet = [
    // Header (20 bytes)
    0, 9,               // Version 9 (2 bytes)
    0, 2,               // FlowSet Count (2 FlowSets in this packet, 2 bytes)
    0, 0, 0, 100,       // Sys Uptime (100 ms, 4 bytes)
    0, 0, 0, 161,       // Unix Timestamp (161 seconds, 4 bytes)
    0, 1, 0, 1,         // Sequence Number (1) and Source ID (1), 4 bytes

    // FlowSet 1: Template FlowSet (ID 1)
    0, 1,               // FlowSet ID (Template FlowSet ID = 1, 2 bytes)
    0, 12,              // FlowSet Length (12 bytes), 2 bytes
    0, 1,               // Template ID (1), 2 bytes
    0, 8,               // Template Length (8 bytes), 2 bytes

    // FlowSet 2: Data FlowSet (ID 2)
    0, 2,               // FlowSet ID (Data FlowSet ID = 2, 2 bytes)
    0, 16,              // FlowSet Length (16 bytes), 2 bytes

    // Flow Record Data:
    0, 0, 0, 1,         // Source IP (192.168.0.1), 4 bytes
    0, 0, 0, 2,         // Destination IP (192.168.0.2), 4 bytes
    1, 80,              // Source Port (80), 2 bytes (big-endian)
    1, 187,             // Destination Port (443), 2 bytes (big-endian)
    0, 6,               // Protocol (TCP = 6), 2 bytes
    0, 0, 0, 100,       // Bytes (100 bytes), 4 bytes
    0, 0, 0, 10,        // Packets (10 packets), 4 bytes

    // Padding bytes to ensure the packet length is 72 bytes
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
];




let fields = vec![
    TemplateField {
        field_type_number: 4,
        field_type: V9Field::Protocol,
        field_length: 2, // IP protocol (TCP=6, UDP=17, etc.)
    },
    TemplateField {
        field_type_number: 8,
        field_type: V9Field::Ipv4SrcAddr,
        field_length: 4, // Source IPv4 address
    },
];

let template = Template {
    field_count: 2,
    template_id: 258,
    fields,
};
let mut parser = NetflowParser::default();
parser.v9_parser.templates.insert(258, template);
let parsed = parser.parse_bytes(&netflow_packet);



i don't get any data back from this, even though the fields exist in the packet

**Comment by mikemiles-dev** [comment]
I can have a look later this evening.  It is hard to tell without the original template data.  I will add better document next release to point to how to define templates.

**Comment by mikemiles-dev** [comment]
Just eye balling it looks like your template ids are not matching.

**Comment by browsified** [comment]
here is another one, if this helps better

let netflow_packet = [
    0, 9,              // Version 9
    0, 2,              // FlowSet count
    0, 0, 9, 9,        // Sys Uptime (4 bytes)
    0, 1, 2, 3,        // Timestamp (4 bytes)
    0, 0, 0, 1,        // Sequence number (4 bytes)
    0, 0, 0, 1,        // Source ID (4 bytes)
    0, 0, 0, 16,       // FlowSet length (4 bytes)

    // Template FlowSet
    1, 2,              // Template ID (2 bytes)
    0, 4,              // Field count (2 bytes) for 4 fields
    0, 1,              // Field Type: Source IPv4 Address (4 bytes)
    0, 4,              // Field Type: Protocol (1 byte)
    0, 8,              // Field Type: IPv4 Source Address (4 bytes)
    0, 12,             // Field Type: IPv4 Destination Address (4 bytes)

    // Data FlowSet (this contains flow record data)
    0, 1,              // Field Type: Source IPv4 Address
    192, 168, 0, 1,    // Source IPv4 Address: 192.168.0.1

    0, 4,              // Field Type: Protocol
    6,                 // Protocol: TCP

    0, 8,              // Field Type: IPv4 Source Address
    192, 168, 0, 1,    // IPv4 Source Address: 192.168.0.1

    0, 12,             // Field Type: IPv4 Destination Address
    192, 168, 0, 2,    // IPv4 Destination Address: 192.168.0.2
];

let fields = vec![
    TemplateField {
        field_type_number: 1, // Source IPv4 Address
        field_type: V9Field::InBytes,
        field_length: 4,      // Length of Source IPv4 Address
    },
    TemplateField {
        field_type_number: 4, // Protocol
        field_type: V9Field::Protocol,
        field_length: 1,      // Length of Protocol (1 byte)
    },
    TemplateField {
        field_type_number: 8, // IPv4 Source Address
        field_type: V9Field::Ipv4SrcAddr,
        field_length: 4,      // Length of IPv4 Source Address
    },
    TemplateField {
        field_type_number: 12, // IPv4 Destination Address
        field_type: V9Field::Ipv4DstAddr,
        field_length: 4,      // Length of IPv4 Destination Address
    },
];

let template = Template {
    field_count: fields.len() as u16,
    template_id: 258, // Template ID
    fields,
};

// Parser setup
let mut parser = NetflowParser::default();
parser.v9_parser.templates.insert(258, template);
let parsed = parser.parse_bytes(&netflow_packet);


Thanks mike for the help

**Comment by mikemiles-dev** [comment]
Sorry earlier I didn't take a closer look but it appears you are providing the template flows so you don't need to additionally specify it yourself.  It looks like you have some inconsistency in some of your examples.  Are these generated by hand or coming from an actual device?

**Comment by mikemiles-dev** [comment]
https://www.ibm.com/docs/en/npi/1.3.0?topic=insight-netflow-v9-formats

**Comment by mikemiles-dev** [comment]
https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html

**Comment by mikemiles-dev** [comment]
So you can use the example like so:

Taking the example from https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html I can craft: 

![Image](https://github.com/user-attachments/assets/bbc5a760-7064-4403-b108-3f55cc027a05)

```rust       let packet = vec![
            0, 9, // Version
            0, 5, // Count Flowsets
            0, 0, 0, 0, // Sys Up Time
            0, 0, 0, 0, // Unix Seconds
            0, 0, 0, 0, // Package Seq
            0, 0, 0, 0, // Source ID
            
            // Template
            0, 0, // Template FlowsSet ID
            0, 28, // Length 28 bytes
            1, 0, // Template Id 256
            0, 5, // Field Count 5
            0, 8, //src adds
            0, 4, // length 4
            0, 13, // Dst Addr,
            0, 4, // Length 4
            0, 15, // Next Hop
            0, 4, // Length 4
            0, 2, // Packets
            0, 4, // Length 4
            0, 1, // Bytes 32
            0, 4 , // Length 4

            // Data
            1, 0, // FlowSet Id
            0, 64, // Length
            0, 0, 0, 0,
            0, 0, 0, 1,
            0, 0, 0, 2,
            0, 0, 0, 3,
            0, 0, 0, 0,
            0, 0, 0, 1,
            0, 0, 0, 2,
            0, 0, 0, 3,
            0, 0, 0, 0,
            0, 0, 0, 1,
            0, 0, 0, 2,
            0, 0, 0, 3,
            0, 0, 0, 0,
            0, 0, 0, 1,
            0, 0, 0, 2,

        ];
```

and I get the following output:

```yaml
  - V9:
      header:
        version: 9
        count: 5
        sys_up_time: 0
        unix_secs: 0
        sequence_number: 0
        source_id: 0
      flowsets:
        - header:
            flowset_id: 0
            length: 28
          body:
            templates:
              - template_id: 256
                field_count: 5
                fields:
                  - field_type_number: 8
                    field_type: Ipv4SrcAddr
                    field_length: 4
                  - field_type_number: 13
                    field_type: DstMask
                    field_length: 4
                  - field_type_number: 15
                    field_type: Ipv4NextHop
                    field_length: 4
                  - field_type_number: 2
                    field_type: InPkts
                    field_length: 4
                  - field_type_number: 1
                    field_type: InBytes
                    field_length: 4
        - header:
            flowset_id: 256
            length: 64
          body:
            data:
              data_fields:
                - 0:
                    - Ipv4SrcAddr
                    - Ip4Addr: 0.0.0.0
                  1:
                    - DstMask
                    - DataNumber: 1
                  2:
                    - Ipv4NextHop
                    - Ip4Addr: 0.0.0.2
                  3:
                    - InPkts
                    - DataNumber: 3
                  4:
                    - InBytes
                    - DataNumber: 0
                - 0:
                    - Ipv4SrcAddr
                    - Ip4Addr: 0.0.0.1
                  1:
                    - DstMask
                    - DataNumber: 2
                  2:
                    - Ipv4NextHop
                    - Ip4Addr: 0.0.0.3
                  3:
                    - InPkts
                    - DataNumber: 0
                  4:
                    - InBytes
                    - DataNumber: 1
                - 0:
                    - Ipv4SrcAddr
                    - Ip4Addr: 0.0.0.2
                  1:
                    - DstMask
                    - DataNumber: 3
                  2:
                    - Ipv4NextHop
                    - Ip4Addr: 0.0.0.0
                  3:
                    - InPkts
                    - DataNumber: 1
                  4:
                    - InBytes
                    - DataNumber: 2

```
