### ISSUE TITLE
IPFIX  enterprise field not parsed correctly in templates

### ISSUE THREAD

**Issue by chandaluri-gupta** [mikemiles-dev/netflow_parser#106]
IPFIX  enterprise field not parsed correctly in templates, however its working as expected in Options Templates

**Comment by mikemiles-dev** [comment]
Can you provide the sample data here or in pcap format?  Do you know what devices created it as well?

**Comment by chandaluri-gupta** [comment]
Thanks for wonderful crate and quick response @mikemiles-dev.   while testing few IPFIX scenarios with templates,  observed this issue.    i am bit new to RUST,  wondering  below snippet seem selectively parsing enterprise field for option templates..

`#[derive(Debug, PartialEq, Eq, Clone, Serialize, Nom)]
#[nom(ExtraArgs(options_template: bool))]
pub struct TemplateField {
    pub field_type_number: u16,
    #[nom(Value(IPFixField::from(field_type_number)))]
    pub field_type: IPFixField,
    pub field_length: u16,
    #[nom(
      
        Cond = "options_template && field_type_number > 32767",
        PostExec = "let field_type_number = if options_template {
                      field_type_number.overflowing_sub(32768).0
                    } else { field_type_number };",
        PostExec = "let field_type = if options_template && enterprise_number.is_some() {
                        IPFixField::Enterprise
                    } else { field_type };"
        
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_number: Option<u32>,
}`

**Comment by mikemiles-dev** [comment]
Hard to tell without some sample data.  Can you provide ?  I can try to look for some online as well.

**Comment by mikemiles-dev** [comment]
I have made a branch called `052` , can you see if that handles it any better?

**Comment by chandaluri-gupta** [comment]
Thanks @mikemiles-dev.    unfortunately the issue still persists.   
a. when field_type_number has  private enterprise number(PEN) bit set in 'templates', it does not correctly extract 'field_type_number' ignoring  PEN bit  which causes mis interpretation of  'type'. 
b. In addition when PEN bit is set,  after field_length,  it should expect the Enterprise Number ,but due to above issue, its treating as regular field_type which is causing wrong parsing  of subsequent fileds ..  

```
- IPFix:
    header:
      version: 10
      length: 138
      export_time: 1670052913
      sequence_number: 0
      observation_domain_id: 0
    flowsets:
      - header:
          header_id: 2
          length: 122
        body:
          templates:
            template_id: 260
            field_count: 14
            fields:
              - field_type_number: 32871
                field_type: Unknown
                field_length: 65535
              - field_type_number: 6321
                field_type: Unknown
                field_length: 32871
              - field_type_number: 65535
```

**Comment by mikemiles-dev** [comment]
Can you please Provide the input data in any way?

**Comment by chandaluri-gupta** [comment]
Here is the sample test input IPFIX data used - 
`[0,10,0,42,99,138,252,49,0,0,0,0,0,0, 0,0,0,2,0,26,1,4,0,2,128,103,255,255,24,177,128,103,255,255,0,0,24,177, 129,64,0,4,0,0,24,177]`

**Comment by mikemiles-dev** [comment]
I think I found the issue, can you try the branch again?

**Comment by mikemiles-dev** [comment]
```yaml
---
source: src/tests.rs
expression: "NetflowParser::default().parse_bytes(&packet)"
---
- IPFix:
    header:
      version: 10
      length: 42
      export_time: 1670052913
      sequence_number: 0
      observation_domain_id: 0
    flowsets:
      - header:
          header_id: 2
          length: 26
        body:
          templates:
            template_id: 260
            field_count: 2
            fields:
              - field_type_number: 32871
                field_type: Unknown
                field_length: 65535
                enterprise_number: 407732327
              - field_type_number: 65535
                field_type: Unknown
                field_length: 0
                enterprise_number: 407732544
```

**Comment by mikemiles-dev** [comment]
I believe I fixed this on the latest release please re open it problem persists

**Comment by chandaluri-gupta** [comment]
@mikemiles-dev ,   Sorry for dealyed response.  The fix works as expected  for  enterprise_number parsing in templates field.  Thanks you.   

Meanwhile,  few additional items related to same found -

a.  field_type  shows as Unknown  , i guess it should show as Enterprise,  also
b.  field_type_number   shows  32871   ( complete u16 value  , it should exclude  enterprise bit while calculating the  filed type number.)  i guess its works in Options Templates  but problem persists in Templates
c.  IPFix data packets  are not recognized data  probably due to  ' unknown field types

**Comment by mikemiles-dev** [comment]
apologies for the oversight.

**Comment by chandaluri-gupta** [comment]
@mikemiles-dev,  sincere thanks for the wonderful work  , nicely organized ,clean library.  i was just putting few observations only.

**Comment by mikemiles-dev** [comment]
Can you try `053` branch?

**Comment by chandaluri-gupta** [comment]
@mikemiles-dev , 053 branch works perfect for parsing the  templates with Enterprise field

a. field_type shows Enterprise correctly

b. field_type_number calculated correctly  now excluding enterprise bit while calculating the filed type number.

c. IPFix data packets are not recognized data enterprise marked fields,  is this expected,  wireshark  CFLOW shows enterprise fields   with hexbytes.

below json of data packet  as empty data_fields.    

For data packets of IPFIX
```
flowsets:
  -header:
        header_id: xxx
        length: xxx
    body:
        data:
            data_fields: []
```
