### ISSUE TITLE
When multiple Flows present in Flowset of IPFIX Data Packet, the parsed data fields not grouped by each flow data

### ISSUE THREAD

**Issue by chandaluri-gupta** [mikemiles-dev/netflow_parser#119]
The parsed data of  IPFIX data packet  with multple flows in given flowset , is returning data as single set, it will be good if its grouped by each flow.

Here is the sample template & test data , from - https://github.com/anonslou/ipfixpcap/blob/master/IPFIX.pcap

```
let packet = [

0x00, 0x0a, 0x05, 0xa0, 0x5b, 0x3b,
0x54, 0x24, 0x01, 0xc8, 0xde, 0x37, 0x00, 0x00, 0x02, 0x00, 0x00, 0x02, 0x00, 0xd4, 0x01, 0x0b,
0x00, 0x22, 0xaf, 0xcc, 0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xaf, 0xcd, 0x00, 0x04, 0x00, 0x00,
0x00, 0x09, 0x00, 0x04, 0x00, 0x01, 0x00, 0xc3, 0x00, 0x01, 0x00, 0xc0, 0x00, 0x01, 0xaf, 0xd1,
0x00, 0x02, 0x00, 0x00, 0x00, 0x09, 0x00, 0xea, 0x00, 0x04, 0x00, 0x5f, 0x00, 0x04, 0x00, 0x3a,
0x00, 0x02, 0x00, 0x0a, 0x00, 0x04, 0x00, 0xef, 0x00, 0x01, 0xa4, 0x24, 0x00, 0x01, 0x00, 0x00,
0x00, 0x09, 0x00, 0x0e, 0x00, 0x04, 0xa4, 0x25, 0x00, 0x01, 0x00, 0x00, 0x00, 0x09, 0x00, 0x16,
0x00, 0x04, 0x00, 0x15, 0x00, 0x04, 0x01, 0x16, 0x00, 0x04, 0x01, 0x17, 0x00, 0x08, 0xa4, 0x57,
0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x4c, 0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x54,
0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x67, 0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x64,
0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x34, 0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x61,
0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x5a, 0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x5b,
0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x5d, 0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x39,
0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0xa4, 0x38, 0x00, 0x04, 0x00, 0x00, 0x00, 0x09, 0x00, 0xe8,
0x00, 0x08, 0x01, 0x2b, 0x00, 0x08, 0x00, 0xe7, 0x00, 0x08, 0x01, 0x2a, 0x00, 0x08, 0x01, 0x0b,
0x04, 0xbc, 0xc2, 0x57, 0xf9, 0x11, 0x0a, 0xcc, 0x65, 0xa6, 0x06, 0x00, 0x31, 0xf4, 0xad, 0x00,
0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x01, 0x10, 0x00,
0x00, 0x00, 0x0d, 0x00, 0x21, 0xa0, 0xc4, 0x4c, 0x21, 0xa0, 0xc4, 0x5e, 0x00, 0x00, 0x00, 0x01,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xcf,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0xc2, 0x57, 0xf9, 0x11, 0x0a, 0xcc, 0x65, 0xa6,
0x06, 0x00, 0x31, 0xf4, 0xae, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00,
0x00, 0x00, 0x0a, 0x01, 0x10, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x21, 0xa0, 0xc4, 0x4c, 0x21, 0xa0,
0xc4, 0x5a, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x05, 0xc5, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x0a, 0xce,
0x65, 0x22, 0x40, 0xe9, 0xa2, 0xbc, 0x06, 0x00, 0x7d, 0x14, 0x6c, 0x00, 0x00, 0x00, 0x00, 0x0d,
0x00, 0x02, 0x08, 0x01, 0x22, 0x00, 0x00, 0x00, 0x0d, 0x01, 0x10, 0x00, 0x00, 0x00, 0x0a, 0x00,
0x21, 0xa0, 0xc4, 0x4e, 0x21, 0xa0, 0xc4, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x59, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x01, 0xc2, 0x57, 0xf9, 0x11, 0x0a, 0xcc, 0x65, 0xa6, 0x06, 0x00, 0x31, 0xf4,
0xaf, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x01,
0x10, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x21, 0xa0, 0xc4, 0x43, 0x21, 0xa0, 0xc4, 0x98, 0x00, 0x00,
0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
0xa8, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x4f, 0xc2, 0x57, 0xf9, 0x11, 0x0a, 0xcc,
0x65, 0xa6, 0x06, 0x00, 0x31, 0xf4, 0xb0, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x50, 0x00,
0x00, 0x00, 0x00, 0x00, 0x0a, 0x01, 0x10, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x21, 0xa0, 0xc4, 0x70,
0x21, 0xa0, 0xc4, 0x90, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x56, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05,
0x0a, 0xce, 0x65, 0x3c, 0xb2, 0xfa, 0x02, 0x52, 0x06, 0x00, 0x7d, 0x01, 0xbb, 0x00, 0x00, 0x00,
0x00, 0x0d, 0x00, 0x01, 0xc5, 0x01, 0x22, 0x00, 0x00, 0x00, 0x0d, 0x01, 0x10, 0x00, 0x00, 0x00,
0x0a, 0x00, 0x21, 0xa0, 0xc4, 0x03, 0x21, 0xa0, 0xf8, 0x12, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00, 0x99, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x5f, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x61, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x9c, 0x00, 0x00,
0x00, 0x64, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x24, 0xdd, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x3b, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x11, 0xc2, 0x57, 0xf9, 0x11, 0x0a, 0xcc, 0x65, 0xa6, 0x06, 0x00,
0x31, 0xf4, 0xb1, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00,
0x0a, 0x01, 0x10, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x21, 0xa0, 0xc4, 0x76, 0x21, 0xa0, 0xc4, 0x98,
0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0xc9, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x27, 0x0a, 0x09, 0x65, 0x05,
0x3e, 0xd2, 0xc4, 0x60, 0x06, 0x00, 0x7e, 0x01, 0xbb, 0x00, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x01,
0xc5, 0x01, 0x22, 0x00, 0x00, 0x00, 0x0d, 0x01, 0x10, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x21, 0xa0,
0xc3, 0xe8, 0x21, 0xa1, 0x11, 0x22, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x23, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x01, 0x6c, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x76, 0x00, 0x00,
0x00, 0x75, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x02, 0x1d, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
0x00, 0x0e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x90, 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x2f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x37, 0x0a, 0xcf, 0x65, 0x8d, 0x57, 0xfa, 0xfa, 0x5b, 0x06, 0x00, 0x3d, 0x01, 0xbb, 0x00,
0x00, 0x00, 0x00, 0x0d, 0x00, 0x02, 0x63, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x02, 0x10, 0x00,
0x00, 0x00, 0x0d, 0x00, 0x21, 0xa0, 0xc4, 0x63, 0x21, 0xa1, 0x03, 0xba, 0x00, 0x00, 0x00, 0x02,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x7b, 0x00, 0x00, 0x00, 0x06,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x01,
0x00, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00, 0x4e, 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00, 0x8a,
0x00, 0x00, 0x00, 0x7b, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x19, 0x85,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x19, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00
        ];
```

sample output section for reference, currently its not grouping by each flow in a given flowset-

 ```
- header:
          header_id: 267
          length: 1212
        body:
          Data:
            fields:
              - 0:
                  - Enterprise
                  - Vec:
                      - 194
                      - 87
                      - 249
                      - 17
              - 1:
                  - Enterprise
                  - Vec:
                      - 10
                      - 204
                      - 101
                      - 166
              - 2:
                  - ProtocolIdentifier
                  - DataNumber: 6
              - 3:
                  - IpDiffServCodePoint
                  - DataNumber: 0
              - 4:
                  - IpTtl
                  - DataNumber: 49
                  - 


              - 0:
                  - Enterprise
                  - Vec:
                      - 194
                      - 87
                      - 249
                      - 17
              - 1:
                  - Enterprise
                  - Vec:
                      - 10
                      - 204
                      - 101
                      - 166
              - 2:
                  - ProtocolIdentifier
                  - DataNumber: 6
              - 3:
                  - IpDiffServCodePoint
                  - DataNumber: 0
```
