### ISSUE TITLE
netflow_parser is not able to parse ipfix packet when both options_temaplate and template are in same message

### ISSUE THREAD

**Issue by Ramanand107** [mikemiles-dev/netflow_parser#121]
**Describe the bug**
netflow_parser is not able to parse ipfix packet when both options_temaplate and template are in same message

**To Reproduce**
1) Attached is the pcap of the ipfix packet.
2) Call parser_bytes on the packet and print the packet.
3) You would see something like below.
  Matched an IPFix Packet: IPFix { header: Header { version: 10, length: 115, export_time: 1744871721, sequence_number: 100000, observation_domain_id: 0 }, flowsets: 
  [FlowSet { header: FlowSetHeader { header_id: 1, length: 14 }, body: Template(Template { template_id: 1256, field_count: 1, fields: [TemplateField { field_type_number: 6, field_type: TcpControlBits, field_length: 34, enterprise_number: None }], padding: [0, 4] }) }] }
4) Though there are 4 flows in the packet the parser has recognised only 1 flow. Also that flow is wrongly recognised as template

5) Below is the sample packet.
000a00736800a129000186a0000000000001000e04e8000100060022000404e80008000000010002002c0102000900080004000c000400070002000b00020004000100020004000100040016000400150004010200214646010178780101303980090600000064077359406800a1296800a129

[ipfix_with_sample_interval.pcap.zip](https://github.com/user-attachments/files/19807775/ipfix_with_sample_interval.pcap.zip)

**Expected behavior**
All 4 flows should be correctly parsed

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikemiles-dev** [comment]
Thanks for the pcap.  I will look at this in the morning.

**Comment by mikemiles-dev** [comment]
Ok here is what seems to be going on.  This is an IPFIX packet but includes a legacy V9 template.  I have not code support for this yet but I guess now is the time to do this.  I will work on this over the weekend.

**Comment by mikemiles-dev** [comment]
Can you try branch `ISSUE_121` and see if this fixes it?

**Comment by Ramanand107** [comment]
Hi Mike,
               Thanks for the code. I got a set of compile issues since you have changed the data type in the below struct.
pub struct IPFixParser {
    pub ipfix_templates: BTreeMap<TemplateId, IPFixTemplate>,
    pub v9_templates: BTreeMap<TemplateId, V9Template>,
    pub ipfix_options_templates: BTreeMap<TemplateId, IPFixOptionsTemplate>,
    pub v9_options_templates: BTreeMap<TemplateId, V9OptionsTemplate>,
}.

I think this is not what we are expecting. We dont need a separate field v9_templates and v9_options_templates. These should be recognzed as regular ipfix templates and ipfix options_templates under their original variable name "templates" and "optiontemplates". The wireshark recognizes the packet as a proper ipfix packet with ipfix fields. Is there any particular reason for considering it as v9 template and vp options template?

**Comment by Ramanand107** [comment]
Hi Mike,
               Thanks for the code. I got a set of compile issues since you have changed the data type in the below struct.
pub struct IPFixParser {
    pub ipfix_templates: BTreeMap<TemplateId, IPFixTemplate>,
    pub v9_templates: BTreeMap<TemplateId, V9Template>,
    pub ipfix_options_templates: BTreeMap<TemplateId, IPFixOptionsTemplate>,
    pub v9_options_templates: BTreeMap<TemplateId, V9OptionsTemplate>,
}.

I think this is not what we are expecting. We dont need a separate field v9_templates and v9_options_templates. These should be recognzed as ipfix templates and ipfix options_templates under their original variable name templates

**Comment by Ramanand107** [comment]
Hi Mike,
               I realized why you used v9 option template due to id=1. I think that was a issue from our test team on how they generated packets. Our requirement is to be able to parse packets with id=2 and id=3 for ipfix. I will ask the test team to update their messages and let know. Will keep you updated

**Comment by mikemiles-dev** [comment]
So if you look at this pcap using wireshark you will see:

![Image](https://github.com/user-attachments/assets/f5699390-c61c-4d3a-92a8-ad5c6568315b)

What happens is the IPFIX supports backwards combability with V9 so in order to parse them I need to use the V9 spec.  I ended up doing some renaming as that in these cases you can tell what a legacy V9 Template + Data is and what regular IPFix Template + Data is.

**Comment by mikemiles-dev** [comment]
> Hi Mike, I realized why you used v9 option template due to id=1. I think that was a issue from our test team on how they generated packets. Our requirement is to be able to parse packets with id=2 and id=3 for ipfix. I will ask the test team to update their messages and let know. Will keep you updated

OK sounds good let me know.  I did some work on the naming to make it less intrusive too.

**Comment by Ramanand107** [comment]
Hi Mike,
               The test team gave the corrected packet. This is correctly decoded in wireshark, but the parser is not able to decode all the fields.
Below is the hex stream:-
[0x00, 0x0A, 0x00, 0x69, 0x68, 0x07, 0x27, 0x23, 0x00, 0x01, 0x86, 0xA0, 0x00, 0x00, 0x00, 0x01, 0x00, 0x03, 0x00, 0x12, 0x04, 0xE8, 0x00, 0x02, 0x00, 0x01, 0x00, 0x01, 0x00, 0x04, 0x00, 0x22, 0x00, 0x04, 0x04, 0xE8, 0x00, 0x0C, 0x00, 0x00, 0x00, 0x64, 0x00, 0x00, 0x00, 0x64, 0x00, 0x02, 0x00, 0x2C, 0x01, 0x02, 0x00, 0x09, 0x00, 0x08, 0x00, 0x04, 0x00, 0x0C, 0x00, 0x04, 0x00, 0x07, 0x00, 0x02, 0x00, 0x0B, 0x00, 0x02, 0x00, 0x04, 0x00, 0x01, 0x00, 0x02, 0x00, 0x04, 0x00, 0x01, 0x00, 0x04, 0x00, 0x16, 0x00, 0x04, 0x00, 0x15, 0x00, 0x04, 0x01, 0x02, 0x00, 0x21, 0x32, 0x01, 0x01, 0x01, 0xC6, 0x07, 0xED, 0x80, 0x30, 0x39, 0x80, 0x09, 0x06, 0x00, 0x00, 0x00, 0x64, 0x07, 0x73, 0x59, 0x40, 0x68, 0x07, 0x27, 0x23, 0x68, 0x07, 0x27, 0x23];

Below is the parser output
`[2025-04-22T06:04:48Z INFO  globalcollector_framework::process::netflow] Successfully stored templates and option templates for 127.0.0.1:37505
[2025-04-22T06:04:48Z DEBUG globalcollector_framework::process::netflow] Matched an IPFix Packet:
 IPFix { header: Header { version: 10, length: 105, export_time: 1745299235, sequence_number: 100000, observation_domain_id: 1 }, 
 flowsets: [FlowSet { header: FlowSetHeader { header_id: 3, length: 18 }, 
 body: OptionsTemplate(OptionsTemplate { template_id: 1256, field_count: 2, scope_field_count: 1, fields: [TemplateField { field_type_number: 1, field_type: OctetDeltaCount, field_length: 4, enterprise_number: None }, TemplateField { field_type_number: 34, field_type: SamplingInterval, field_length: 4, enterprise_number: None }], padding: [] }) }] }

`

**Comment by Ramanand107** [comment]
[ipfix_option_scope_sample.pcapng.zip](https://github.com/user-attachments/files/19844278/ipfix_option_scope_sample.pcapng.zip)

[ipfix_option_scope_sample.pcapng.zip](https://github.com/user-attachments/files/19844281/ipfix_option_scope_sample.pcapng.zip)

**Comment by mikemiles-dev** [comment]
So just to confirm what I am seeing.  The parser successful parsers the first 3 sets, just we are not seeing the last set which is 1 flow of data.

```yaml
 IPFix:
  header:
    version: 10
    length: 105
    export_time: 1745299235
    sequence_number: 100000
    observation_domain_id: 1
  flowsets:
    - header:
        header_id: 3
        length: 18
      body:
        OptionsTemplate:
          template_id: 1256
          field_count: 2
          scope_field_count: 1
          fields:
            - field_type_number: 1
              field_type: OctetDeltaCount
              field_length: 4
            - field_type_number: 34
              field_type: SamplingInterval
              field_length: 4
    - header:
        header_id: 1256
        length: 12
      body:
        OptionsData:
          fields:
            - 0:
                - OctetDeltaCount
                - DataNumber: 100
            - 1:
                - SamplingInterval
                - DataNumber: 100
    - header:
        header_id: 2
        length: 44
      body:
        Template:
          template_id: 258
          field_count: 9
          fields:
            - field_type_number: 8
              field_type: SourceIpv4address
              field_length: 4
            - field_type_number: 12
              field_type: DestinationIpv4address
              field_length: 4
            - field_type_number: 7
              field_type: SourceTransportPort
              field_length: 2
            - field_type_number: 11
              field_type: DestinationTransportPort
              field_length: 2
            - field_type_number: 4
              field_type: ProtocolIdentifier
              field_length: 1
            - field_type_number: 2
              field_type: PacketDeltaCount
              field_length: 4
            - field_type_number: 1
              field_type: OctetDeltaCount
              field_length: 4
            - field_type_number: 22
              field_type: FlowStartSysUpTime
              field_length: 4
            - field_type_number: 21
              field_type: FlowEndSysUpTime
              field_length: 4
```
